version: '2.1'
orbs:
   node: circleci/node@4.3
   gh: circleci/github-cli@1.0
workflows:
   test-and-release:
      jobs:
         - gh/release:
              notes-file: changelog.md
              tag: 1.0.0
              title: The test release
              context:
                 - GITHUB_CREDENTIALS
              filters:
                 branches:
                    only:
                       - develop
