version: 2.1
orbs:
   node: circleci/node@4.3
   gh: circleci/github-cli@1.0

jobs:
   build-native:
      executor: node/default
      steps:
         - checkout
         - node/install-packages:
              pkg-manager: yarn
         - run:
              name: Swap node versions
              command: |
                 set +e
                 wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
                 export NVM_DIR="$HOME/.nvm"
                 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
                 nvm install v16
                 echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
                 echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
         - run:
              name: Decrypt keystore
              command: cd apps/native/android/app && openssl aes-256-cbc -d -in onlinelibrary.keystore.encrypted -k $DECRYPTION_KEY -md md5 >> onlinelibrary.keystore
         - run:
              name: Generate assets
              command: cd apps/native/android && yarn assets
         - run:
              name: Generate apk
              command: cd apps/native/android && yarn apk

workflows:
   main:
      jobs:
         - build-native
         - gh/release:
              tag: 1.0.0
              title: The test release
              context:
                 - GITHUB_CREDENTIALS
              filters:
                 branches:
                    only:
                       - main
